local ox_questions = 
{
	-- Basic difficulty level!
	[1] = {				
		{
			{ "A player's shop can hold up to 40 slots", false },
			{ "A player's shop can hold up to 45 slots", true },
		},
		{
			{ "Agility Potion gives 15% moving speed", true },
			{ "Agility Potion gives 20% moving speed", false },
		},
		{
			{ "A maximum of 7 people can be in one party", false },
			{ "A maximum of 8 people can be in one party", true },
		},
		{
			{ "Jug-Hyul is a pig", false },
			{ "Jug-Hyul is a wolf", false },
		},
		{ "Remove Magic can remove the effects of Dance with Wind", true },
		{ "At the Fox Hunt Event you have to kill all the foxes from the Desert to earn a prize", false },
		{ "The Saleswoman's name is Kim", true },
		{ "The maximum Fishing Pole refine level is +9", false },
		{ "The Peddler has regular offers for exchanging an upgrade item for another", true },
		{ "Mrs. Soon's first name is Aranyo", true },
		{
			{ "Mr. Soon is hiding from his wife to study peacefully", true },
			{ "Mr. Soon hated reading when he was a little boy", false },
			{ "Mr. Soon has never been good with swords", true },
		},
		{ "You won't lose any experience points when reviving from dead if your level is 20 or less", false },
		{ "You get to choose your sub class at Level 4", false },
		{ "The maximum number of players in a group is 6", false },
		{ "You can read a tome again after using an Exorcism Scroll", true },
		{ "You can only train your horse once a day", false },
		{ "Pony training quests can only fail by dismounting horse", true },
		{ "Arrows can only be shot whilst on foot", false },
		{ "You can never step on water", false },
		{ "You can't enter the Fireland at level 30", false },
		{ "You become married when you get teleported to the wedding map", false },
		{ "All maps can be accessed through a red teleporting portal", false },
		{ "You can't change the name of your pet", false },
		{
			{ "Tainted Pet Cheheoms give less points than pure Pet Cheheoms", false },
			{ "Pure Pet Cheheoms can fail", false },
			{ "There are four types of Pet Cheheoms", false },
		},
		{ "You can't betray your own kingdom by moving to another", false },
		{ "Iceking is the boss of the Mountain Sohan", false },
		{ "Stone Ape drops Horse Medals", true },
		{
			{ "You can create a party with players from another kingdom", false },
			{ "You cannot create a party with players from another kingdom", true },
		},
		{ "The teleporter can take you to Snakefield", false },
		{ "Mu-Rang is known for making rice cakes", false },
		{
			{ "Bera drops Bear Foot Skin", false },
			{ "Bera drops Bear Foot Skin+", true },
		},
		{ "Amethyst Necklace makes you invulnerable to magic attacks", false },
		{ "You cannot gain Rank Points while you are fishing", false },
		{ "If you can catch a Goldfish, it will grant you a wish", false },
		{ "You can take off item mall Thief Gloves", false },
		{
			{ "Jin-Hee's gender is male", false },
			{ "Jin-Hee is not human", false },
		},
		{ "Green Changer works on Level 30 weaponry", true },
		{ "Green Changer works on accesories below Level 30", false },
		{
			{ "Purple Potion (M) increases movement speed by 30", false },
			{ "Purple Potion (S) increases movement speed by 20", false },
		},
		{ "You can own a pet after you reach Level 35", false },
		{ "You can reset your skills at the Old Lady until Level 50", false },
		{ "Skill Reset Scroll from Item Mall never fails", true },
		{ "You can switch channels while you are doing the horse traning without failing the trial", true },
		{ "You need to be at least Level 70 to drop a Reaper's Chest", true },
		{ "A military horse can be fed with Hay", false },
		{ "You can do mining past Level 30", true },
		{ "A player shop will remain open even if there is no more items to sell", false },
		{
			{ "You can have up to 3 pets", false },
			{ "You can have up to 3 mounts", false },
		},
		{ "Any class can jump over obstacles", false },
		{ "Some NPCs move from their original position over the course of a day", true },
		{ "Exorcism Scrolls work on Soul Stone Training", false },
		{ "The stones you put in your equipment are called metin", false },
		{ "Bottomless Wallet isn't tradeable", true },
		{ "You can catch fish in Dark Dragons Maps", false },
		{ "Tiger monsters can only be found in your hometown, Imha and the Firelands", false },
		{
			{ "The Bonus \"Strong against Animals\" works against spiders", false },
			{ "The Bonus \"Strong against Animals\" works against snakes", true },
		},
		{ "You have to wait 10h until you can deliver another Ice Marble", false },
		{ "Yu-Hwan is a secret agent working for the Captain", true },
		{ "To access the second floor of the Spider Dungeon you need to be at least Level 10", false },
		{ "You earn rank points within safe zones", false },
		{
			{ "You can use wedding rings inside Spider Dungeon", true },
			{ "You can use wedding rings inside Spider Dungeon 2", false },
		},
		{
			{ "Honobo Dungeon Herb revives a Military Horse", false },
			{ "Joklor Dungeon Herb revives an Armed Horse", false },
		},
		{ "Elixir of Agility restores HP", false },
		{ "The maximum level a pet can reach is 99", false },
		{ "Guild maps can be accessed from a Teleporter", true },
		{ "The Old Lady asks for two Wedding Rings to marry you", false },
		{ "The Blacksmith gives you a free upgrade if you carry out a one-time task for him", true },
		{ "Taurean is scared of the monsters around the village", true },
		{ "Ape Lord drops Honobo Dungeron Herb", false },
		--{ "Clam has a chance to give you a pebble", true },
		{ "The Coffer of Wisdom can only be received by winning an OX Tournament", true },
		{ "Yu-Hwan works for the Guardian", false },
		{ "The City Guard is in charge of training the newest recruits", true },
		{ "Jinno is the Kingdom of war while Shinsoo is the Kingdom of trade", true },
		{ "You can drink Elixir of Agility at Level 16", true },
		{ "You can wear a Golden Necklace at level 21", false },
		{ "Using a fishbot will get you banned", true },
		{ "Max level on the server is 99", false },
		{ "A normal skill book success rate is 50%", true },
		{
			{ "Eun-Jung is Level 26", true },
			{ "Hungry Red Boar is Level 10", true },
			{ "Jug-Hyul is Level 10", true },
			{ "Dispirited Mi-Jung is Level 23", true },
			{ "Cung-mok is Level 8", false },
			{ "Wild Dog is Level 2", false },
		},
		{
			{ "Blessing Spell increases reflect chance", false },
			{ "Blessing Spell reduces physical damage", true },
		},
		{ "Heuk-Young can upgrade stones", false },
		{ "You can create Red Liquids at Yu-Hwan", false },
		{
			{ "P Enchanted Blade absorbs 12% of HP", true },
			{ "P Enchanted Blade absorbs 11% of HP", false },
			{ "P Enchanted Damage absorbs 12% of HP", false },
		},
		{ "You can bet for yourself at The Dojang", true },
		{ "Metin of Combat can spawn Tigers", false },
		{ "You need 13000 rank points to be Chivarlic", false },
		{ "Level 25 is needed to get married", true },
		{ "It is possible to get Chance of Faint on a Shield", false },
		{ "Demon Tower has a total of eight floors", false },
		{ "It is possible to get a poison resistance bonus", true },
		{ "Gold Shoes give Poison Resistance", false },
		{ "Amethyst Necklace gives HP Regeneration", true },
		{
			{ "A Band of Oblivion restores 1 skill point", true },
			{ "A Band of Oblivion restores all skill points at once", false },
		},
		{ "Ebony Necklace can be worn from level 34", false },
		{ "Golden Necklace gives Arrow Resistance", true },
		{ "The maximum Magic Resistance bonus in a bracelet is 20%", false },
		{ "It is impossible to get Undead bonus in a bracelet", false },
		{ "Bamboo Skin Shoes give Lightning Resistance", false },
		{ "Wolf can very rarely drop an Antler Bow", false },
		{ "Old Lady wears a skirt", false },
		{ "Cure can also remove poison", true },
		{ "Betrayer's name is Dalso", false },
		{ "Goo-Pae cannot be found at the Kingdom's second city", false },
		{ "Desert Fox is level 25", true },
		{ "You need a Wedding Ring to get married", false },
		{
			{ "Imha is in Shinsoo", false },
			{ "Joan is in Shinsoo", false },
			{ "Joan is in Chunjo", true },
			{ "Jayang is in Chunjo", false },
			{ "Jayang is in Shinsoo", true },
			{ "Imha is in Jinno", true },
		},
		{
			{ "Uriel is a woman", false },
			{ "Uriel is a man", true },
		},
		{
			{ "Turquoise Dress is for Level 9", true },
			{ "Pink Dress is for Level 9", false },
		},
		{
			{ "There are 10 Fishermen in Shinsoo.", true},
			{ "There are 9 Fishermen in Shinsoo.", false},
			{ "There are 7 Fishermen in Jinno.", false},
			{ "There are 8 Fishermen in Jinno.", true},
		},
		{
			{ "Metin of Combat is level 15.", false },
			{ "Metin of Combat is level 10.", true },
		},
		{
			{ "There is no Level 20 Metin Stone", false },
			{ "Metin of Greed is a Level 25 Metin Stone", false },
			{ "Metin of Greed spawns on the second town map of the Kingdom", false },
		},
		{
			{ "Evil Bl. Storm Joh-Hwa can drop a Piece of Gem", true },
			{ "Black Wind To-Su can drop a Piece of Gem", false },
		},
		{
			{ "Chief Orc has three heads", false },
			{ "Chief Orc has two heads", true },
		},
		{
			{ "Black Round Shield can be worn at level 45", true },
			{ "Black Round Shield can only be worn from level 45", false },
		},
		{
			{ "Gold Bracelet gives poison resistance", true },
			{ "Gold Bracelet gives chance to poison", false },
		},
		{
			{ "Stone Ape is a boss of easy ape dungeon.", true},
			{ "Golden Ape is a boss of easy ape dungeon.", false},
			{ "Ape Lord can be found in Honobo Dungeon.", false},
		},
	}, 

	[2] = {
		{ "There are no maps with more than three different types of Metin Stones", false },
		{ "Mr.Soon holds a book in his left hand", false },
		{ "The maximum Demi-Human additional bonus in a weapon is 10%", true },
		{ "Hong-Hae wears a blue dress", false },
		{ "Dragon Knife+5 has got an attack speed of 20%", false },
		{ "Black Magic Armour+5 has a bonus of -10% movement speed", true },
		{ "Silver Bracelet +7 gives +500 HP", true },
		{ "You need 2x Snake Tail and a Clam to upgrade Ant Lion suit to +9", true },
		{ "You need 2x Scorpion Needle and a Fishbone to upgrade Leather Shoes to +7", false },
		{ "2x White Flag is needed to upgrade War Scythe to +5", false },
		{ "Black Tunic+8 gives 136 defence", false },
		{ "2x Orc Tooth and a Clam are needed to upgrade Ebony Earrings to +8", true },
		{ "Black Magic Armour+7 gives 132 defence", true },
		{ "A Jade Necklace +2 gives +9 Casting speed", false },
		{ "Ebony Earrings +1 give +60 HP", false },
		{ "Pearl Necklace +9 gives +6 Inteligence", false },
		{ "Jade Necklace +3 gives +2 Strenght", false },
		{ "Silver Necklace +4 gives +8 Casting Speed", false },
		{ "Gold Shoes +6 give 12% moving speed", true },
		{ "Metin of Shadow can only be found in Dragon Valley", false },
		{
			{ "Grilled Grass Carp gives 20% attack speed", true },
			{ "Grilled Grass Carp gives 20% moving speed", false },
		},
		{ "Ah-Yu's baby has black hair", true },
		{ "2x Spider Legs are required to upgrade Dragon Scale Shield to +5", true },
		{ "Tiger Monk Shield +7 gives 87 defence and 12% resistance to Assassins", true },
		{ "Lion Edge Shield +9 gives 20% resistance to Warriors", false },
		{ "2x Yeti's Fur and a Blue Pearl are required to upgrade Fire Bird Shoes to +8", true },
		{ "Phoenix Shoes +8 give 8% chance to block", false },
		{ "2x Snake Skin and a Clam is needed to upgrade Pearl Bracelet to +9", true },
		{ "A White Pearl and Demon Gem is needed to upgrade Crystal Bracelet to +7", false },
		{ "2x Unknown Medicine is needed to upgrade Heaven Tear Necklace to +5", true },
		{ "Giant Tortoise is level 69", false },
		{ "Hae-Tae is level 59", false },
		{ "Heaven Tear Earrings +9 gives 12 intelligence", false },
		{ "There is a Sura Skeleton in Heaven's Lair 2", true },
		{ "Level 65 metins can only be found in Demon Tower", false },
		{ "Warrior Ghost lets you enter the Dragon Lair", false },
		{ "You need 2x Shuriken to upgrade White Gold Bracelet to +6", false },
		{
			{ "Grilled Mandarin Fish restores 220 SP", false },
			{ "Grilled Loach can make you invisible for 5 minutes", true },
			{ "Grilled Lotus fish restores 1200 HP", true },
			{ "Grilled Striped Bass gives Agility", false },
			{ "Grilled Smelt gives chance to poison", true },
			{ "Grilled Shiri gives strength against monsters", true },
			{ "Grilled Salmon restores 360 SP", false },
			{ "Grilled Pikes increases Agility", true },
			{ "Grilled Catfish restores 500 SP", true },
			{ "Grilled Rainbw Trout restores 600 HP", false },
			{ "Grilled Eel gives strength for 5 minutes", false },
			{ "Grilled Gold Crucian gives resistance against skills", true },
			{ "Grilled Tenchi restores HP", true },
			{ "Grilled Mirrow Carp gives vitality", false },
		},
		{ "+7 Crystal Bracelet has got 35% HP regeneration", false },
		{ "Blue Dragon Breath is used to upgrade spirit stones from +4 to +5", true },
		{ "Flying Wizard Sword+6 has got an atack value of 107-133", false },
		{ "Demon Blade +9 has got 25% Chance to take the SP of an enemy", false },
		{ "Horned Helmet +7 gives 68 defense", false },
		{ "Mean Red Spider is lvl 52", false },
		{ "A level 13 guild can hold up to 56 members", true },
		{ "Crystal Earrings+4 gives a bonus of +8 agility", false },
		{ "Bronze Boots +5 gives 5% poison resistance", false },
		{ "The bonus HP regeneration can be obtained on an armour", false },
		{ "The Tritonic Soldier is a human with shark-like features", true },
		{ "Taurean is wearing a pinafore", true },
		{ "The White Rabbit is holding a paintbrush", true },
		{ "Se-Rang has her eyes closed all the time", true },
		{ "Ogre Magus can use magic powers", true },
		{ "You have to wait 10h until you can deliver another Ice Marble", false },
		{ "The NPC who pays the highest price for the Lump of Gold is Uriel", false },
		{
			{ "Soul Crystal Earring +5 provides a bonus of 8% Strong against Monsters", false },
			{ "Soul Crystal Earring +5 provides a bonus of 9% Strong against Monsters", true },
		},
		{
			{ "Pets receive half the experience you get while leveling", false },
			{ "Pets receive the same amount of experience you get while levelling", false },
			{ "Pets receive double the experience you get while levelling", true },
		},
		{
			{ "Jong-Chug sells Pet Seals for 12kk Yang", false },
			{ "Jong-Chug sells the Reindeer Pet Seal", false },
		},	
		{ "Perception is increased by Green Cheheom", false },
		{ "The Tiger is the most perceptive of all pets", false },
		{
			{ "Pets can only be evolved after level 40", false },
			{ "Pets need to be at least level 50 to be evolved", true },
			{ "Pets can only be evolved at level 100", false },
		},
		{ "You need 2000 rank points to raise one skill from G3 to G4", false },
		{ "Only characters over Level 60 can drop items if they have negative rank", false },
		{ "If there is a maintenance, offline shops with offtime available will remain open", true },
		{
			{ "There is a level 5 bell", false },
			{ "There is a level 45 bell", false },
		},
		{
		   { "Leather Shoes+9 provides a bonus of 12% movement speed", false },
		   { "Leather Shoes+9 provides a bonus of 20% movement speed", false },
		   { "Dragon Scale Shield has a -12% moving speed penalty", false },
		   { "Dragon Scale Shield has a -6% moving speed penalty", true },
		},
		{ "You can buy a pickaxe from an NPC regardless of your level", true },
		{ "There's a guild war mode that involves carrying a flag", true },
		{ "Assassins can throw more than one dagger while attacking on horseback", true },
		{ "Shamans can throw more than one fan while attacking on horseback", true },
		{ "At the Fox Hunt event you have to kill all the foxes from the Desert to earn a prize! ", false },
		{ "Yu-Rang is famous for making Spider Eye Soup", false },
		{ "Fighting Tigers drop Tiger Claw", false },
		{ "Reviving a Military Horse requires 1.000.000 Yang and Joklor Dungeon Herb", false },
		{ "Mirine's brother used to hunt with Yang-Shin", true },
		{ "The Level 40 Biology Quest's Soul Stone drops from the Demon Tower", false },
		{ "Level 70 Biology Quest's Soul Stone can be dropped from naturally spawning monsters at Red Wood Forest", false },
		{ "To set bonuses on your party you need the Leadership skill of level M1 or higher", false },
		{ "Having 10 points on leadership allows you to set bonuses on your party members", true },
		{ "Pets can be evolved onto mounts only after level 51 has been reached", false },
		{ "You can have up to 90% magic resistance", false },
		{ "You can upgrade Dark Dragon items on the town or guild Blacksmiths", false },
		{ "Storekeeper hates frog leg soup", false },
		{ "Secret books have a higher success chance than the skill books", true },
		{ "Tome books have a higher success chance than Secret books", false },
		{
			{ "You can only find Desert Foxes at events", false },
			{ "There are Desert Foxes on Snakefield", false },
		},
		{ "Kenki spawns on the bottom right corner of the Snakefield", true },
		{ "Curse Book+ can be dropped outside the Dark Temple", true },
		{ "There are bosses with the same monster difficulty level as Metin Stones", true },
		{ "There are 5 monsters classed as bosses inside the Demon Tower", false },
		{ "Dragon's Strenght skill gives you a bright aura around your feet", false },
		{ "Razador is one of Red Dragon's minions", false },
		{ "For the level 70 Biologist Quest you need to collect 20 Ghost Tree Branches", false },
		{ "Lv 80 biologist quest rewards you with +8% more damage towards other players", false },
		{ "Horse Stomp is available for military horses starting from level 55", false },
		{ "You can use the betrayal quest only once", true },
		{ "Yonah suffers from asthma", true },
		{
			{ "Baek-Go is Doctor Raphel", true },
			{ "Baek-Go is one of the agents of Geto", true },
		},
		{ "Maximum Poison Resist is 8%", false },
		{ "Fishing Pole doesn't lose a level if your upgrade fails", true },
		{ "Pickaxe doesn't lose a level if its upgrade fails", true },
		{ "Shooting arrows with a bow on a dagger assassin will take SP from you", true },
		{
			{ "Prices for items at NPCs are tripled when you are outside your kingdom", true },
			{ "Prices for items at NPCs are doubled when you are outside your kingdom", false },
		},
		{ "Ariyoung gives you the Clothing for the Dealer Question request", true },
		{ "The General Store will provide you the linen for the Dealer Question request", false },
		{ "2x Bear Gall+ are needed to upgrade Tiger Plate Armour to +7", false },
		{ "2x Bear Gall are needed to upgrade Tiger Plate Armour to +7", true },
		{ "Biologist Chaegirab wears glasses without lenses", true },
		{ "Uriel wears glasses without lenses", false },
		{ "There are 3 Horses and 3 Ponies at Stable Boy", false },
		{ "There are 2 Horses and 2 Ponies at Stable Boy", true },
		{ "There are 10 Fishermen in Shinsoo", true },
		{ "There are 9 Fishermen in Shinsoo", false },
		{ "There are 7 Fishermen in Jinno", false },
		{ "There are 8 Fishermen in Jinno", true },
		{ "Fear decreases opponents attack power", true },
		{ "Fear increases opponents attack power", false },
		{ "2x snake tail+ is needed to upgrade a level 48 armour to +6", false },
		{ "2x snake tail+ is needed to upgrade a level 48 armour to +5", true },
		{ "White Oath Archer can drop White Flag", false },
		{ "Savage Archer can drop White Flag", false },
		{ "Desert Outlaw can drop white flag", true },
		{ "Vein of Ebony Ore can only be found in map 2", false },
		{ "Vein of Fossil Trunk Ore can be found in Ice Mountain", false },
		{ "Silver Bracelet +9 gives +1000 HP", false },
		{
			{ "White Oath Archer can drop White Flag.", false},
			{ "Savage Archer can drop White Flag.", false},
			{ "Desert Outlaw can drop white flag.", true},
		},
		{
			{ "Silver Bracelet +7 gives +500 HP.", true},
			{ "Silver Bracelet +9 gives +1000 HP.", false},
		},
		{
			{ "You need level 69 to wear Black Steel Armour +7", true },
			{ "You need level 66 to wear Black Wind Suit +8", false },
		},
		{
			{ "White Gold Bracelet +9 gives +1800 HP", true },
			{ "White Gold Bracelet +0 gives +50 HP", false },
		},
		{
			{ "Jade Shoes +9 gives 5% chance for double experience.", true},
			{ "Jade Shoes +9 gives 5% experience bonus.", false},
		},
		{
			{ "Storekeeper holds a butcher knife.", true},
			{ "Storekeeper holds a butcher knife in his left hand.", false},
			{ "Storekeeper holds a butcher knife in his right hand.", true},
		},
		{
			{ "Proud Demon King can spawn his minions.", false},
			{ "Demon King can spawn his minions.", true},
		},
		{
			{ "Bestial Captain is level 32.", true},
			{ "Bestial Captain is level 47.", false},
		},
		{
			{ "Metin of Soul can not drop a Soul Stone.", false},
			{ "Metin of Shadow can drop a Soul Stone.", true},
		},
		{
			{ "Demon King can drop a box.", false},
			{ "Elite Demon King can drop a box.", true},
		},
		{
			{ "Queen Spider has only 6 legs.", false},
			{ "Queen Spider is level 60.", true},
		},
		{
			{ "Vein of Ebony Ore can only be found in map 2.", false},
			{ "Vein of Fossil Trunk Ore can be found in Ice Mountain.", false},
		},
		{
			{ "Only Plagued Archer drops Arrow Heads.", false},
			{ "Only Angry Plagued Archer drops Arrow Heads.", true},
		},
		{
			{ "Immortal Ghost can only be found on floor 9 of Demon Tower.", false},
			{ "Death Reaper can only be found on floor 9 of Demon Tower.", true},
		},
		{
			{ "Amethyst Bracelet gives HP restoration.", false},
			{ "Amethyst Bracelet gives SP regeneration.", true},
		},
		{
			{ "Heaven Tear Bracelet +8 gives 9% chance of Critical.", true},
			{ "Heaven Tear Bracelet +9 gives 10% chance of Penetration.", false},
		},
	},

	[3] = {
		{ "Dance with Wind will let you go over the maximum speed limit of 200", true },
		{
			{ "The Wedding Planner wears a delightfully red dress", false },
			{ "The Wedding Planner wears a bright blue dress", false },
			{ "The Wedding Planner wears a black and blue dress", false },
			{ "The Wedding Planner wears a white and gold dress", false },
		},
		{
			{ "Freezing reduces enemies' movement and attack speeds", true },
			{ "Some classes are less affected by freezing effects than others", false },
			{ "The Freezing effect can only be cause by other players' skills", false },
		},
		{ "A Level 13 Guild can hold up to 56 members.", true},
		{ "Kouri Rings do not reduce Earth Dragon's regeneration frequency, only its amount", false },
		{ "Mr. Soon didn't believe that the Treasure Map could lead to an actual treasure.", true },
		{ "You can create Red Liquids at Yu-Hwan.", false},
		{ "The Battle Sword's highest attack value at +6 equals 203.", true },
		{
			{ "In the Legendary Akuma questline, one of the victims has a wife named Eda.", true },
			{ "In the Legendary Akuma questline, one of the victims has a wife named Sira.", false },
		},
		{ "The main story quest 'Destroy the Metin Stones!' rewards 75000 Yang upon completion.", false },
		{ "In a perfect world scenario, giving Chaegirab all Demon's Keepsakes takes 84 hours.", true },
		{ "Cassim will never offer you more than 150.000 Yang for additional Vizto weapon drops.", false },
		{
			{ "Shinsoo hometown has a small peninsula.", true },
			{ "Shinsoo hometown does not have any peninsulas.", false },
			{ "Jinno hometown does not have any peninsulas.", false },
			{ "Jinno hometown has a small peninsula.", true },
			{ "Chunjo hometown has a small peninsula.", false },
			{ "Chunjo hometown does not have any peninsulas.", true },
		},
		{ "Wooden Necklace+8 provides a bonus of 15% Fire Resistance.", false },
		{
			{ "There are 2 Bestial Captains per channel.", true },
			{ "There are 3 Bestial Captains per channel.", false },
		},
		{
			{ "No monsters that float above ground naturally spawn on Mountain Sohan.", false },
			{ "No monsters that float can naturally spawn on Dragon Valley.", false },
		},
		{
			{ "Harang's dream is to become a Healing Mage, so she can assist allies in the battle.", true },
			{ "Harang's dream is to become a Dragon Mage, so she can assist the soldiers in the battle.", false },
		},
		{
			{ "There are a total of 43 fishermen across all areas.", false },
			{ "There are over 20 fishermen across the entire world.", true },
		},
		{ "Shooting an arrow as an Assassin from the Stealth Combat will take SP from you.", true },
		{
			{ "The NPC who pays the highest price for three Lump of Gold delivered in a row is Uriel.", false },
			{ "The NPC who pays the highest price for three Lump of Gold delivered in a row is the Old Lady", true },
			{ "The NPC who pays the highest price for the first Lump of Gold delivered to them is the Captain", false },
		},
		{
			{ "Earth Dragon inflicts Inner Decay.", true },
			{ "You can heal Inner Decay by heading to the Cleansing Seals.", true },
			{ "Inner Decay will cause instant death after 5 seconds pass.", false },
			{ "In order to be affected by Earth Dragon's Inner decay, you need to be physically hit by it.", false },
		},
		{ "It's possible to socket stones into the Emperor Armor.", true },
		{ "Lightning Resistance works against Heaven Cleric from within Heaven's Lair 2.", true },
		{ "Dark Resistance works on enemies from within the Devil's Catacomb.", true },
		{ "Strong against Animals works on Snakefield monsters.", true },
		{ "You need 2x White Hairbands to upgrade a Crescent Sword to +8.", false },
		{ "It's possible to fully master two pet battle skills", false },
		{ "It's possible to use military combat maneuvers on armed horses.", false },
		{ "Elite Demon Key can be stored on the Safebox.", true },
		{ "Switfness provides 50% movement speed at Perfect Master.", false },
		{ "Walking Ape wears a skirt.", false },
		{
			{ "Tigris wears a red hearted collar.", true },
			{ "Tigris wears a blue spiral collar.", false },
		},
		{
			{ "There's a floating hexagon on Aqua Dragon's Lair.", false },
			{ "There's a floating crystal on Aqua Dragon's Lair.", true },
			{ "Aqua Dragon's Lair lamps are made of small crystals.", true },
			{ "There are dragons drawn all over the floor on Aqua Dragon's Lair.", true },
		},
		{ "Goo-Pae wears shoes.", false },
		{ "Razador can burn you.", false },
		{ "Frost Troll has blue eyes.", false },
		{ "The Diabolical Hermit has 6 legs.", true },
		{ "You need defeat 10 Claw Poison Spider for the horse training quest number 17.", true },
		{ "One of Uriel's lenses is broken.", false },
		{ "The Nameless Flowers are yellow.", true },
		{ "Soon and Yonah are the only male NPCs with familes.", false },
		{ "Yonah uses glass as a material for his works.", true },
		{ "Yu-Hwan used to be a king advisor in the past.", true },
		{ "The Plagued monsters that have invaded Mountain Sohan used to be soldiers.", true },
		{ "Yang-Shin is a baker whenever he's not hunting.", false },
		{ "Ariyoung has had a crush on David for a long time.", false },
		{ "Ariyoung has a young child.", false },
		{
			{ "Ah-Yu's husband perished in the war and she raises her child alone.", true },
			{ "Ah-Yu's husband is fighting battles far away, and ocassionally visits her.", false },
		},
		{ "Aranyo is in charge of creating the uniforms that soldiers and recruits wear.", true },
		{ "The Peddler does not collect rare items.", true },
		{
			{ "Lee Chung is Geto, the 35th commander of Gate Keepers.", true },
			{ "Lee Chung is Geto, the 45th commander of Gate Keepers.", false },
		},
		{ "Octavio considers a dish from another country made with Mosquito Eyes as an excellent work of cousine.", true },
		{ "You can not vote for yourself in the Monarch Election.", false },
		{
			{ "Armoursmith's name is Stanton.", true },
			{ "Armoursmith's name is Stanley.", false },
			{ "Weaponsmith's name is Stanley.", true },
			{ "Accessorysmith's name is Stanley.", false },
		},
		{
			{ "General Store's father is the Weapon Shop Dealer.", false },
			{ "General Store's father is the Armour Shop Dealer.", true },
		},
		{
			{ "Warrior Aqua Armour +9 raises your defense by 242.", false },
			{ "Warrior Aqua Armour +9 provides you with 15% Resistance against Skill Damage.", true },
		},
		{
			{ "There are 3 Horses and 3 Ponies at Stable Boy.", false },
			{ "There are 2 Horses and 2 Ponies at Stable Boy.", true },
		},
		{
			{ "You can find 5 Sura Skeletons in Heaven's Lair.", false },
			{ "You can find 6 Sura Skeletons in Heaven's Lair.", true },
		},
		{
			{ "Flame Warrior has four legs.", false},
			{ "Flame Soldier has four legs.", true},
		},
		{	
			{ "Ice Bug has 6 legs.", false},
			{ "Ice Bug has 8 legs.", true},
		},
		{
			{ "Dragon Valley is made out of 19 islands.", true},
			{ "Dragon Valley is made out of 10 islands.", false},
		},
		{
			{ "You neeed 25 Ice Marbles for a Biologist quest.", false},
			{ "You need 25 Ghost Tree Branches for a Biologist quest.", true},
		},
		{
			{ "There are 10 platforms in Dark Temple.", true},
			{ "There are 8 platforms in Dark Temple.", false},
		},
		{
			{ "There are Giants in Snakefield.", false},
			{ "Giants can only be found in Giants Wasteland.", false},
		},
		{ "There are Aloe Vera plants in the Yongbi Desert.", true },
	}
}

for level, qlist in ipairs(ox_questions) do
	for idx, question in ipairs(qlist) do
		if type(question[1]) == 'table' then
			-- Question group
			for group, subquestion in ipairs(question) do
				add_ox_quiz(level, idx, subquestion[1], subquestion[2])
			end
		else
			add_ox_quiz(level, idx, question[1], question[2])
		end
	end
end